#!/usr/bin/env node
'use strict';
// Local revisit must retain the same model and saved-version identity.
const fs=require('fs'),http=require('http'),assert=require('assert/strict');
const {chromium}=require('playwright');
const html=fs.readFileSync(require('path').resolve(__dirname,'../../dart-search/web/modelter/index.html'));
const server=http.createServer((req,res)=>{if(req.url.startsWith('/e')){res.writeHead(204);res.end();return;}res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(html);});
(async()=>{
  let browser,n=0;const check=(v,m)=>{assert.ok(v,m);n++;};
  try{
    await new Promise(r=>server.listen(0,'127.0.0.1',r));
    browser=await chromium.launch(process.env.CHROME_BIN?{executablePath:process.env.CHROME_BIN}:{});
    const page=await browser.newPage(),errors=[];
    page.on('pageerror',e=>errors.push(String(e)));page.on('dialog',d=>d.accept(d.type()==='prompt'?'Revisit audit':''));
    const url='http://127.0.0.1:'+server.address().port+'/';
    await page.goto(url);
    await page.locator('#slotSave').click();
    const saved=await page.evaluate(()=>({ws:WS,price:state.price}));
    await page.reload();
    const after=await page.evaluate(()=>({ws:WS,price:state.price,button:document.getElementById('slotSave').textContent}));
    if(process.argv.includes('--reproduce')){
      await page.evaluate(()=>document.getElementById('rrDemoA').click());
      const beforeRR=await page.evaluate(()=>({rr:!!(window.rrModel&&rrModel.on),irr:simModel().raw.IRR}));
      await page.reload();
      const afterRR=await page.evaluate(()=>({rr:!!(window.rrModel&&rrModel.on),irr:simModel().raw.IRR}));
      console.log(JSON.stringify({saved,after,beforeRR,afterRR},null,2));return;
    }
    check(after.ws.dealId===saved.ws.dealId,'saved deal remains attached after reload');
    check(after.ws.versionId===saved.ws.versionId&&after.ws.savedHash===saved.ws.savedHash,'saved version identity retained');
    check(await page.evaluate(()=>!wsDirty()),'clean saved version remains clean');
    check(after.button.includes('v0.2'),'reload offers next version, not duplicate deal');
    await page.locator('#f_price').fill('130000');await page.locator('#f_price').press('Tab');
    check(await page.evaluate(()=>wsDirty()),'manual edit marks saved version dirty');
    await page.reload();
    check(await page.evaluate(()=>parseNum(state.price)===130000&&wsDirty()&&WS.dealId!==null),'dirty edit and identity persist together');
    await page.locator('#slotSave').click();await page.reload();
    check(await page.evaluate(()=>!wsDirty()&&wsDeal().versions.length===2),'saving dirty edit creates one clean version');
    await page.evaluate(()=>wsLoadVersion(WS.dealId,wsDeal().versions[0].id));await page.reload();
    check(await page.evaluate(()=>wsVersion(wsDeal(),WS.versionId).n===1&&!wsDirty()),'selected older version survives reload');
    await page.evaluate(()=>document.getElementById('rrDemoA').click());
    const rr=await page.evaluate(()=>({irr:simModel().raw.IRR,leases:rrModel.leases}));
    check(await page.evaluate(()=>!WS.dealId),'sample deal detaches previous saved deal');
    await page.evaluate(()=>{rrModel.leases[0].name='PRIVATE_TENANT';rrState.raw='PRIVATE_RAW_FILE';update();});
    check(await page.evaluate(()=>!localStorage.getItem('mt_state').includes('PRIVATE_')),'auto-save excludes tenant name and raw upload');
    await page.reload();
    check(await page.evaluate(()=>!!(window.rrModel&&rrModel.on&&rrModel.confirmed)&&!window.rrState),'active normalized rentroll restores without source file');
    check(Math.abs((await page.evaluate(()=>simModel().raw.IRR))-rr.irr)<1e-10,'rentroll IRR is unchanged on revisit');
    await page.evaluate(()=>document.querySelector('[data-rr-clear]').click());await page.reload();
    check(await page.evaluate(()=>!window.rrModel),'rentroll off stays off');
    for(const deal of ['office','logistics','dev','refi']){
      await page.locator('.deal-tab[data-k="'+deal+'"]').click();await page.reload();
      check(await page.evaluate(d=>cur===d&&!WS.dealId&&!window.rrModel,deal),deal+' switch restores correct detached model');
    }
    await page.evaluate(()=>{cur='office';fillExample();state.price='111000';exTouch('price');update();});
    const original=await page.evaluate(()=>localStorage.getItem('mt_state'));
    const payload=await page.evaluate(()=>{const p=sharePayload();p.s={...p.s,price:'190000'};return mtLZ.compress(JSON.stringify(p));});
    await page.goto(url+'?test='+Date.now()+'#v='+payload);check(await page.evaluate(()=>window.__mtReadonly&&state.price==='190000'),'read-only share opens supplied deal');
    check(await page.evaluate(()=>localStorage.getItem('mt_state'))===original,'opening shared model preserves local draft');
    await page.reload();check(await page.evaluate(()=>localStorage.getItem('mt_state'))===original,'shared reload still preserves local draft');
    await page.locator('#roOpen').click();
    check(await page.evaluate(()=>!window.__mtReadonly&&!WS.dealId&&JSON.parse(localStorage.getItem('mt_state')).s.price==='190000'),'explicit own-model action creates detached local draft');
    const own=await page.evaluate(()=>localStorage.getItem('mt_state'));
    await page.goto(url+'?test='+Date.now()+'#t=logistics&src=seo');
    check(await page.evaluate(()=>localStorage.getItem('mt_state'))===own,'search landing does not overwrite local work');
    await page.waitForTimeout(500);check(await page.locator('#f_price').evaluate(e=>e===document.activeElement),'search landing focuses numeric first field');
    await page.locator('#f_price').fill('175000');await page.locator('#f_price').press('Tab');
    check(await page.evaluate(()=>JSON.parse(localStorage.getItem('mt_state')).s.price.replace(/,/g,'')==='175000'),'explicit edit adopts search example as new draft');
    await page.evaluate(()=>localStorage.setItem('mt_state',JSON.stringify({c:'office',d:'standard',s:{asset:'Legacy',price:'110000'},k:{},r:{}})));
    await page.goto(url);check(await page.evaluate(()=>state.asset==='Legacy'&&!WS.dealId&&!window.rrModel),'legacy draft restores without new fields');
    for(const bad of ['{','null','[]','{"c":"office","s":[]}','{"c":"office","s":{},"rr":{"leases":{}}}']){
      await page.evaluate(s=>localStorage.setItem('mt_state',s),bad);await page.reload();check(await page.evaluate(()=>!!simModel()&&!WS.dealId),'corrupt draft falls back safely: '+bad);
    }
    await page.setViewportSize({width:390,height:844});
    await page.goto(url+'?test='+Date.now()+'#t=office&src=seo');await page.waitForTimeout(500);
    check(await page.evaluate(()=>!document.activeElement.matches('input,textarea,select')),'mobile landing avoids opening keyboard');
    await page.locator('#sampleStartBtn').click();await page.locator('#f_price').fill('125000');await page.locator('#f_price').press('Tab');await page.reload();
    check(await page.evaluate(()=>parseNum(state.price)===125000),'mobile edit survives reload');
    await page.locator('#slotSave').click();
    const clean=await page.evaluate(()=>({n:wsDeal().versions.length,hash:WS.savedHash,db:localStorage.getItem('mt_deals')}));
    await page.locator('#f_price').fill('135000');await page.locator('#f_price').press('Tab');
    await page.evaluate(()=>{window.realSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='mt_deals')throw new DOMException('full','QuotaExceededError');return realSetItem.call(this,k,v);};});
    await page.locator('#slotSave').click();
    const failed=await page.evaluate(()=>({n:wsDeal().versions.length,hash:WS.savedHash,db:localStorage.getItem('mt_deals'),dirty:wsDirty()}));
    check(failed.n===clean.n&&failed.hash===clean.hash&&failed.db===clean.db&&failed.dirty,'failed version write does not create a phantom saved version');
    await page.evaluate(()=>{cur='refi';fillExample();});await page.locator('#slotSave').click();
    check(await page.evaluate(()=>!WS.dealId&&Object.keys(wsDB().deals).length===Object.keys(JSON.parse(localStorage.getItem('mt_deals')).deals).length),'failed new-deal write leaves no in-memory fake saved deal');
    await page.evaluate(()=>{Storage.prototype.setItem=realSetItem;});
    await page.evaluate(()=>{cur='office';fillExample();document.getElementById('rrDemoA').click();rrModel.leases[0].name='PRIVATE_TENANT';});
    await page.locator('#slotSave').click();await page.reload();
    check(await page.evaluate(()=>!!rrModel&&!wsDirty()&&!localStorage.getItem('mt_deals').includes('PRIVATE_TENANT')),'saved rentroll stays clean and excludes names');
    await page.locator('#fillExample').click();
    check(await page.evaluate(()=>!WS.dealId&&!rrModel),'example reset detaches a saved rentroll deal');
    await page.locator('#slotSave').click();await page.evaluate(()=>clearAll());await page.reload();
    check(await page.evaluate(()=>!WS.dealId&&!rrModel&&!Object.keys(state).length),'clear remains detached and empty after reload');
    await page.goto(url+'?sample='+Date.now()+'#t=office&src=seo');
    await page.evaluate(()=>document.getElementById('rrDemoA').click());await page.reload();
    check(await page.evaluate(()=>!!rrModel&&rrModel.on),'explicit rentroll sample adopts landing and survives reload');
    await page.evaluate(()=>{rrState={leases:rrModel.leases.map((l,i)=>({...l,name:i<2?'PRIVATE_DUP':'PRIVATE_OTHER'}))};update();});
    const top=await page.evaluate(()=>rrRiskMetrics(rrState.leases,10000).top1);
    const topText=()=>page.locator('#rrRiskBody .mx-item').filter({hasText:'최대 임차인 비중'}).locator('.mx-v').innerText();
    check((await topText()).startsWith((top*100).toFixed(0)+'%'),'visible unmasked concentration groups repeated tenant');
    await page.evaluate(()=>{state.rrmask='1';update();});
    check((await topText()).startsWith((top*100).toFixed(0)+'%'),'masking labels preserves visible concentration');
    check(await page.evaluate(()=>rrDisplayName('PRIVATE_DUP',0)===rrDisplayName('PRIVATE_DUP',1)),'screen/Excel aliases share one identity for repeated tenant');
    const groupedLink=await page.evaluate(()=>encodeState());
    const receiver=await browser.newPage();await receiver.goto(url+'?group=1#v='+groupedLink);
    check((await receiver.locator('#rrRiskBody .mx-item').filter({hasText:'최대 임차인 비중'}).locator('.mx-v').innerText()).startsWith((top*100).toFixed(0)+'%'),'shared read-only view preserves masked concentration');
    await receiver.close();
    await page.reload();
    check(await page.evaluate(()=>rrRiskMetrics(rrModel.leases,10000).top1)===top,'same tenant across contracts retains anonymous concentration grouping');
    check((await topText()).startsWith((top*100).toFixed(0)+'%'),'reloaded visible masked concentration stays unchanged');
    check(await page.evaluate(()=>!localStorage.getItem('mt_state').includes('PRIVATE_')),'concentration grouping stores no actual tenant name');
    await page.locator('#slotSave').click();
    await page.evaluate(()=>{
      const d=wsDeal(),v=d.versions[0];v.snap.rr.leases.forEach((l,i)=>l.name=i<2?'LEGACY_PRIVATE':'LEGACY_OTHER');
      let h=2166136261>>>0;for(const c of wsStable(v.snap)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}v.hash=('0000000'+h.toString(16)).slice(-8);
      wsPersist();wsLoadVersion(d.id,v.id);
    });
    check(await page.evaluate(()=>!wsDirty()),'legacy named version loads clean using canonical hash');
    await page.reload();check(await page.evaluate(()=>!!WS.dealId&&!wsDirty()),'legacy named version stays attached and clean after reload');
    await page.locator('#f_price').fill('160000');await page.locator('#f_price').press('Tab');await page.reload();
    check(await page.evaluate(()=>parseNum(state.price)===160000&&wsDirty()&&!!WS.dealId),'legacy named version retains later dirty edit');
    await page.evaluate(()=>renderWsPanel());
    const snap=await page.evaluate(()=>{const s=sharePayload();s.s={...s.s,price:'170000'};return 'MTSNAP1:'+mtLZ.compress(JSON.stringify(s))+':PANSTM';});
    await page.locator('#wsXlsxRestore').setInputFiles({name:'snapshot.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(snap)});
    await page.waitForFunction(()=>state.price==='170000');
    check(await page.evaluate(()=>!WS.dealId),'xlsx original restore detaches unrelated saved version');
    await page.reload();check(await page.evaluate(()=>state.price==='170000'&&!WS.dealId),'xlsx original restore becomes current local draft');
    await page.evaluate(()=>{cur='office';fillExample();depth='deep';renderForm();restoreInputs();update();});
    await page.locator('#scenOn').check();
    await page.locator('[data-scen="down_exitcap"]').fill('6.25');
    await page.locator('#slotSave').click();await page.reload();
    check(await page.evaluate(()=>scenOn&&scenState.down_exitcap==='6.25'&&!wsDirty()),'saved scenario survives reload as clean version');
    check(await page.locator('[data-scen="down_exitcap"]').inputValue()==='6.25','restored scenario appears in editable field');
    await page.locator('[data-scen="down_exitcap"]').fill('7.25');await page.reload();
    check(await page.evaluate(()=>scenState.down_exitcap==='7.25'&&wsDirty()),'unsaved scenario edits survive reload and remain dirty');
    await page.locator('#slotSave').click();
    await page.evaluate(()=>wsLoadVersion(WS.dealId,wsDeal().versions[0].id));
    check(await page.evaluate(()=>scenState.down_exitcap==='6.25'&&!wsDirty()),'version switch restores its own scenario');
    check(await page.evaluate(()=>{const d=wsDeal(),second=d.versions[1].snap;let seen;wsWithSnapshot(second,()=>seen=scenState.down_exitcap);return seen==='7.25'&&scenState.down_exitcap==='6.25';}),'temporary export applies scenario and restores working state');
    await page.evaluate(()=>{
      const d=wsDeal(),v=d.versions[0];delete v.snap.sc;
      let h=2166136261>>>0;for(const c of wsStable(v.snap)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}v.hash=('0000000'+h.toString(16)).slice(-8);
      wsPersist();wsLoadVersion(d.id,v.id);
    });
    check(await page.evaluate(()=>!scenOn&&!Object.keys(scenState).length&&!wsDirty()),'old versions without scenarios default off and clean');
    const count=await page.evaluate(()=>Object.keys(wsDB().deals).length);
    await page.evaluate(()=>{window.realSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='mt_deals')throw new DOMException('full','QuotaExceededError');return realSetItem.call(this,k,v);};});
    check(await page.evaluate(()=>{const before=localStorage.getItem('mt_deals');try{wsImportFile(wsExportFile(WS.dealId));return false;}catch(e){return before===localStorage.getItem('mt_deals');}}),'failed import throws instead of reporting success');
    check(await page.evaluate(()=>Object.keys(wsDB().deals).length)===count,'failed import rolls back memory');
    const quota=await page.evaluate(()=>({id:WS.dealId,v:WS.versionId,n:wsDeal().versions.length,db:localStorage.getItem('mt_deals')}));
    await page.evaluate(()=>wsDeleteVersion(WS.dealId,WS.versionId));
    check(await page.evaluate(q=>WS.versionId===q.v&&wsDeal().versions.length===q.n&&localStorage.getItem('mt_deals')===q.db,quota),'failed version delete rolls back memory and selection');
    await page.evaluate(()=>wsDeleteDeal(WS.dealId));
    check(await page.evaluate(q=>WS.dealId===q.id&&!!wsDeal()&&localStorage.getItem('mt_deals')===q.db,quota),'failed deal delete keeps current saved deal');
    await page.evaluate(()=>{Storage.prototype.setItem=realSetItem;});
    await page.locator('.deal-tab[data-k="logistics"]').click();
    check(await page.evaluate(()=>!scenOn&&!Object.keys(scenState).length),'new deal does not inherit previous scenario');
    await page.goto(url+'?upload='+Date.now()+'#t=office&src=seo');
    await page.evaluate(()=>document.querySelector('[data-rr-open]').click());
    await page.locator('#rrPaste').fill('임차인\t임대면적(평)\t보증금(원)\t월임대료(원)\t월관리비(원)\t계약시작\t계약만기\nPRIVATE_UPLOAD\t2000\t1440000000\t120000000\t42000000\t2022-03\t2027-02');
    await page.locator('#rrParse').click();await page.locator('#rrApply').click();
    const applied=await page.evaluate(()=>simModel().raw.IRR);
    await page.reload();
    check(await page.evaluate(()=>!!rrModel&&rrModel.leases.length===1&&!location.hash),'explicit uploaded rentroll adopts tagged landing as draft');
    check(Math.abs((await page.evaluate(()=>simModel().raw.IRR))-applied)<1e-10,'uploaded rentroll keeps same calculation on reload');
    check(await page.evaluate(()=>!localStorage.getItem('mt_state').includes('PRIVATE_UPLOAD')),'uploaded tenant name stays out of automatic storage');
    await page.goto(url+'?source='+Date.now()+'#t=office&src=seo');
    const paused=await page.evaluate(()=>localStorage.getItem('mt_state'));
    await page.evaluate(()=>srcPop());
    check(await page.evaluate(()=>localStorage.getItem('mt_state'))===paused,'opening source modal does not adopt landing');
    await page.locator('[data-srck="price"]').selectOption('실사');
    check(await page.evaluate(()=>!location.hash&&JSON.parse(localStorage.getItem('mt_state')).st.price.s==='실사'),'actual source edit adopts and immediately stores draft');
    await page.reload();check(await page.evaluate(()=>srcTags.price.s==='실사'),'source-only edit survives reload');
    await page.goto(url+'?depth='+Date.now()+'#t=office&src=seo');
    await page.evaluate(()=>document.querySelector('[data-depth="deep"]').click());await page.reload();
    check(await page.evaluate(()=>depth==='deep'&&!location.hash),'manual depth change adopts landing');
    await page.goto(url+'?adjust='+Date.now()+'#t=office&src=seo');
    await page.evaluate(()=>{adjSet(ADJ_DEFS.office[3],7.5);update();});await page.reload();
    check(await page.evaluate(()=>stackState.senior_rate==='7.5'&&!location.hash),'manual rate adjustment adopts landing');
    check(errors.length===0,'no uncaught browser errors: '+errors.join('; '));
    console.log('RETENTION OK - '+n+' checks');
  }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
